name: Deploy sovisys.com to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          script: |
            set -e
            
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            cd /var/www/www.sovisys.com
            
            echo "➡️  Pulling latest changes from GitHub..."
            GIT_SSH_COMMAND="ssh -i /root/.ssh/sovisys_deploy_key -o IdentitiesOnly=yes" git pull

            echo "➡️  Installing dependencies and building..."
            pnpm install
            pnpm build
            
            echo "✅ www.sovisys.com deployment successful!"
