name: Deploy sovisys.com to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          script: |
            set -e
            
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            cd /var/www/www.sovisys.com
            
            echo "➡️  Pulling latest changes from GitHub..."
            sudo git pull

            echo "➡️  Setting final permissions..."
            sudo chown -R ubuntu:www-data .
            sudo find . -type d -exec chmod 775 {} \;
            sudo find . -type f -exec chmod 664 {} \;
            if [ -d "node_modules/.bin" ]; then
              sudo find node_modules/.bin -type f -exec chmod +x {} \;
            fi
            
            echo "➡️  Installing dependencies..."
            pnpm install

            echo "➡️  Building the project..."
            pnpm build
            
            echo "✅ www.sovisys.com deployment successful!"
