name: Deploy sovisys.com to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          
          script: |
            set -e
            
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            cd /var/www/www.sovisys.com
            
            echo "➡️  Pulling latest changes from GitHub..."
            # Note: It's better practice to not use sudo for git pull if possible.
            # See the "Further Improvements" section below.
            sudo GIT_SSH_COMMAND="ssh -i /root/.ssh/sovisys_deploy_key -o IdentitiesOnly=yes" git pull

            echo "➡️  Setting ownership for build process..."
            sudo chown -R ubuntu:ubuntu .

            echo "➡️  Installing dependencies..."
            pnpm install
            
            echo "➡️  Granting execute permission to esbuild..."
            # This is the new line that fixes the issue.
            # We use a wildcard (*) for the esbuild version to make the script more robust.
            chmod +x ./node_modules/.pnpm/@esbuild+linux-x64*/node_modules/@esbuild/linux-x64/bin/esbuild
            
            echo "➡️  Building the project..."
            pnpm build
            
            echo "✅ www.sovisys.com deployment successful!"
